name: CI for Scala3doc

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v2

      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Compile and test
        run: ./project/scripts/sbt scala3doc/test

      - name: Locally publish self
        run: ./project/scripts/sbt scala3doc/publishLocal

      - name: Generate test documentation
        run: ./project/scripts/sbt scala3doc/generateSelfDocumentation

      - name: Generate Scala 3 documentation
        run: ./project/scripts/sbt scala3doc/generateScala3Documentation

      - name: Generate documentation for example project using dotty-sbt
        run: ./project/scripts/sbt "sbt-dotty/scripted sbt-dotty/scala3doc"

      - name: Upload documentation to server
        uses: azure/CLI@v1
        env: 
          AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}
        with:
          inlineScript: |
            DOC_DEST=$([ $GITHUB_REF = "refs/heads/master" ] && echo master || echo pr-$(echo $GITHUB_REF | cut '-d/' -f3))
            echo uplading docs to https://scala3doc.virtuslab.com/$DOC_DEST
            az storage container create --name $DOC_DEST --account-name scala3docstorage --public-access container
            az storage blob sync -s scala3doc/output -c $DOC_DEST --account-name scala3docstorage
